language: ruby

rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1

services:
  - postgresql

before_script:
  - psql -c 'create database simpleadmin_prototype_test;' -U postgres
  - bundle exec rake db:migrate
