rvm:
  - 2.4.1
language: ruby

addons:
  postgresql: 9.4

before_script:
  - psql -c 'create database example_app_test;' -U postgres
  - gem install rails
  - bundle install

script: xvfb-run bundle exec rspec
